#!/bin/bash

set -a

# cloudserver cluster ip
CLOUDSERVER_ENDPOINT=zenko.local:80
CLOUDSERVER_HOST=zenko.local

# Zenko account credentials
ZENKO_STORAGE_ACCOUNT_ACCESS_KEY=
ZENKO_STORAGE_ACCOUNT_SECRET_KEY=
# default is us-east-1
AWS_S3_BACKEND_SOURCE_LOCATION=us-east-1

# AWS credentials/info
AWS_S3_BACKEND_ACCESS_KEY=
AWS_S3_BACKEND_SECRET_KEY=
AWS_S3_BACKBEAT_BUCKET_NAME=
# AWS site name
AWS_S3_BACKEND_DESTINATION_LOCATION=

# Azure credentials/info
AZURE_BACKEND_ACCOUNT_NAME=
AZURE_BACKEND_ACCESS_KEY=
AZURE_BACKEND_ENDPOINT=
AZURE_BACKBEAT_CONTAINER_NAME=
# Azure site name
AZURE_BACKEND_DESTINATION_LOCATION=

# GCP credentials/info
GCP_BACKEND_SERVICE_KEY=
GCP_BACKEND_SERVICE_EMAIL=
GCP_CRR_BUCKET_NAME=
# GCP site name
GCP_BACKEND_DESTINATION_LOCATION=

set +a
