apiVersion: v1
kind: Pod
metadata:
  name: debug-kafka-cli
spec:
  containers:
  - name: debug-kafka-cli
    image: solsson/kafka:0.11.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
